---
title: "Cover Letter"
output:
  pdf_document:
    latex_engine: xelatex
fontsize: 11pt
geometry: margin=1in
---

Dear Editor,  

We sincerely thank you, the Associate Editor, and the reviewers for the time and effort devoted to evaluating our manuscript *“Evaluating the impact of log-normal bias-correction on a state-space stock assessment model” (CJFAS-2025-0093)*. We are very pleased that the manuscript has been accepted for publication.  

We confirm that all requested revisions have been incorporated in the final version of the manuscript. In addition, the data and code underlying this study are publicly available at:  
- GitHub: [https://github.com/lichengxue/Bias_Correction_Project](https://github.com/lichengxue/Bias_Correction_Project)  
- Zenodo archive (DOI): [https://doi.org/10.5281/zenodo.17253797](https://doi.org/10.5281/zenodo.17253797)  

We greatly appreciate your guidance, the Associate Editor’s handling of the review process, and the constructive feedback from the reviewers, which have significantly improved the clarity and quality of this work.  

Thank you again for your support throughout the review process.  

Sincerely,  

Chengxue Li (Corresponding Author)  
on behalf of all co-authors  
